### ISSUE TITLE
Use try-with when opening resources

### ISSUE THREAD

**Issue by ricardoekm** [ricardoekm/Kyrix#4]
It's recommended to use try-with when opening resources to avoid resource leakage. 

https://github.com/ricardoekm/Kyrix/blob/0ce6879a307f1d16440ef79fa978d9dc529020a2/back-end/src/main/java/main/Main.java#L65-L68

**Comment by tracyhenry** [comment]
also tracked here: https://github.com/tracyhenry/Kyrix/issues/15
and an initial impl: https://github.com/tracyhenry/Kyrix/pull/133
